# Generated by Django 4.2.30 on 2026-06-15 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kolesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='ad',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_path',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='cars/', verbose_name='Фото автомобиля'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('sold', 'Продано')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_path',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='avatars/', verbose_name='Путь к аватару'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Контактный телефон'),
        ),
        migrations.AlterModelTable(
            name='ad',
            table='ads',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
